title: Heet Patel
logo: /assets/img/logo.jpg
description: I'm a curious individual who loves using machine learning and data analytics to find insights and solve complex business problems. I strive to contribute my knowledge, logical thinking, and analytical skills to help organizations grow and develop while continuously learning and collaborating with others.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
