title: Heet Patel
logo: /assets/img/logo.jpg
description: AI,ML,CV,NLP. Curious individual who loves using machine learning and data analytics to find insights and solve complex business problems.Currently grad Student at Concordia.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
