title: Heet Patel
logo: /assets/img/logo.jpg
description: Masters Student at Concordia University, working in the field of Data science and Ai.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
