title: Heet Patel
logo: /assets/img/logo.jpg
description: Curious individual who loves using machine learning and data analytics to find insights and solve complex business problems.Currently grad Student at Concordia. Have previously worked in AI,ML,CV,NLP.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
